### ISSUE TITLE
Reevaluate persistent storage requirements

### ISSUE THREAD

**Issue by makentenza** [rht-labs/enablement-ci-cd#4]
We are using persistent storage for every single component of the enablement (Nexus, Jenkins, MongoDB...). Apart from the shared GitLab no persistent storage should be required

**Comment by springdo** [comment]
Jenkins should have a PV; it's likely to need restarting. As does Nexus as you don't want to loose Binaries. I believe Tom Page has already written a PR for the Mongo aspect. @makentenza can you review his PR below please?
https://github.com/rht-labs/enablement-ci-cd/pull/1

**Comment by springdo** [comment]
I've updated the mongodb in the todolist-api app too.

**Comment by losito** [comment]
When going through the enablement last week, I faced a problem where 2Gi wasn't enough when trying to troubleshoot little bugs such as spelling errors. One thing I faced is the Jenkinsfile allows for the retention of the previous 10 builds. I think we could reduce it to 1. Refer to line 24 in the Jenkinsfile of the todolist-api in the following link https://github.com/rht-labs/todolist-api/blob/feature/jenkinsfile/Jenkinsfile. The same goes for the front end.

**Comment by pcarney8** [comment]
personally i like it when Jenkins _doesn't_ have a PV, it can jack things up due to it saving the Jenkins configuration in that PV (aka jenkins slaves can't call home to get the remoting jar due to inaccurate route names, etc)

**Comment by makentenza** [comment]
Mongo is moved to ephemeral and I think we have seen benefits already during the training on having persistent storage for both Nexus and Jenkins, so can we agree on close this @springdo @pcarney8?

**Comment by springdo** [comment]
Sounds good to me!
