### ISSUE TITLE
Dedicated Nodes for container Builds

### ISSUE THREAD

**Issue by makentenza** [rht-labs/enablement-ci-cd#5]
We should evaluate on having dedicated Nodes just for containers builds. Builds are intensive during the enablement sessions so it would probably make sense to get some dedicated Nodes just for this purpose.

**Comment by springdo** [comment]
Happy for you to explore this! One of the things we could do to speed things up anyway is to try have the `jenkins-slave-npm` already built and ready to rock. @makentenza can we share one image across everyones `<NAME>-ci-cd` namespace for Jenkins to be able to consume it?

**Comment by makentenza** [comment]
Yes, we can put the slave under `openshift` namespace which will be accessible for everyone. Just need to test if Jenkins will be intelligent enough to get that image just with the name. Let's make a test

**Comment by springdo** [comment]
Cool - why don't we see if we can get @tompage1994 to  start that experiment / test

**Comment by springdo** [comment]
Moving this issue to the `enablement-docs` where all the other ones are!
